[package]
name = "goldsrc-rs"
version = "0.12.1"
authors = ["r4v3n6101 <raven6107@gmail.com>"]
edition = "2021"
license = "MIT"
description = "Collection of file's parsers for goldsrc engine."
repository = "https://github.com/r4v3n6101/goldsrc-rs/"
keywords = ["goldsrc", "gamedev", "parsing"]
categories = ["parsing", "rendering::data-formats", "game-development"]

[dependencies]
static_assertions = "1"
smallstr = "0.3"
byteorder = "1.5"

[dev-dependencies]
glob = "0.3"
image = "0.25"
