[package]
name = "goldsrc-rs"
version = "0.7.0"
edition = "2021"

[dependencies]
static_assertions = "1"
smol_str = "0.1.23"
nom = { version = "7.1.1", optional = true }
byteorder = { version = "1.4.3", optional = true }

[dev-dependencies]
glob = "0.3.0"
image = "0.24.3"