[package]
name = "goldsrc-rs"
version = "0.7.2"
authors = ["r4v3n6101 <raven6107@gmail.com>"]
edition = "2021"
license = "MIT"
description = "Collection of file's parsers for goldsrc engine."
repository = "https://github.com/r4v3n6101/goldsrc-rs/"
keywords = ["goldsrc", "gamedev", "parsing"]
categories = ["parsing", "rendering::data-formats", "game-development"]

[features]
default = ["byteorder"]

[dependencies]
static_assertions = "1"
smol_str = { version = "0.1.23", default-features = false }
byteorder = { version = "1.4.3", optional = true }
nom = { version = "7.1.1", optional = true }

[dev-dependencies]
glob = "0.3.0"
image = "0.24.3"